# Site settings
title: One More Admin - Erik Gomez
email: e@eriknicolasgomez.com
description: > # this means to ignore newlines until "baseurl:"
  A place where I complain about Apple and occasionally write
  interesting things. Just one more admin putting thoughts 
  into the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.eriknicolasgomez.com" # the base hostname & protocol for your site
twitter_username: Contains_ENG
github_username:  erikng
author: Erik Gomez

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge
sass:
    sass_dir: _sass

paginate: 6
permalink: pretty
gems:
  - jekyll-seo-tag

# Jekyll SEO Tag
twitter:
  username: Contains_ENG
logo: /images/banner.jpg
social:
  name: Erik Gomez
  links:
    - https://twitter.com/Contains_ENG
    - https://www.linkedin.com/in/eriknicolasgomez
    - https://github.com/erikng
defaults:
  - scope:
      path: ""
    values:
      image: /images/banner.jpg
