# Site settings
title: One More Admin
email: e@eriknicolasgomez.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.eriknicolasgomez.com" # the base hostname & protocol for your site
twitter_username: Contains_ENG
github_username:  erikng

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge
sass:
    sass_dir: _sass
